Repository fumihub/PigLead, pull requests merged in 2020-11, with the labels that each got.

#118 Develop kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/CalendarData.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/ScheduleDataSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/PigLeadUtils.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/ViewModelFactory.kt
Labels: タスク

#119 Issue 115 Calendar関連のkotlin移行
  CalenderView/app/build.gradle
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarViewModel.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/MainActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListBindings.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/CalendarData.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/ScheduleRepository.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/ScheduleDataLocalSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/SchedulesDao.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/remote/ScheduleDataRemoteSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/AppCompatActivityExt.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/AppExecutors.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/Injection.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/ViewModelFactory.kt
  CalenderView/app/src/main/res/layout/calendar_fragment.xml
  CalenderView/app/src/main/res/layout/calendar_fragment_screen_slide_page.xml
  CalenderView/app/src/main/res/layout/schedule_fragment.xml
Labels: タスク, 優先度：高

#120 Develop kt
  CalenderView/app/build.gradle
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarViewModel.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/MainActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListBindings.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/CalendarData.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/ScheduleRepository.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/ScheduleDataLocalSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/SchedulesDao.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/remote/ScheduleDataRemoteSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/AppCompatActivityExt.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/AppExecutors.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/Injection.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/ViewModelFactory.kt
  CalenderView/app/src/main/res/layout/calendar_fragment.xml
  CalenderView/app/src/main/res/layout/calendar_fragment_screen_slide_page.xml
  CalenderView/app/src/main/res/layout/schedule_fragment.xml
Labels: タスク

#121 Issue 114
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorSelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/listAdapter.kt
Labels: タスク

#122 #114 Kotlin移行
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
Labels: タスク

#127 #126 修正をコミット
  CalenderView/app/src/main/res/layout/color_create.xml
  CalenderView/app/src/main/res/layout/input_main.xml
  CalenderView/app/src/main/res/layout/list_cell.xml
Labels: タスク

#128 #110 の修正をコミット
  CalenderView/app/src/main/AndroidManifest.xml
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorSelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/listAdapter.kt
Labels: タスク

#129 #111 InputFormの変数コメントを追記をコミット
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorSelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/listAdapter.kt
Labels: タスク

#131 #130 warningが出ている箇所を修正
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
Labels: 優先度：高

#132 #130 warningが出る箇所修正
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorSelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/listAdapter.kt
Labels: タスク
