Repository fumihub/PigLead, pull requests merged in 2021-09, with the labels that each got.

#171 #170 家計簿入力画面の初期値を0に変更 & 数値入力タップ時にリセットする機能を削除
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
  CalenderView/app/src/main/res/layout/input_balance_main.xml
Labels: バグ, 優先度：高

#174 #169 家計簿０円入力抑止追加
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
Labels: バグ, タスク, 優先度：中

#183 #178 #181 開始時間よりも終了時間が早い場合のエラー処理、成功トースト追加
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategorySelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
Labels: バグ, 優先度：中
