Repository fumihub/PigLead, pull requests merged in 2021-07, with the labels that each got.

#161 Enterを押したら¥0になる問題解消
  CalenderView/app/build.gradle
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListBindings.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/ScheduleDataSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/ScheduleRepository.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/ScheduleDataLocalSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/SchedulesDao.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/remote/ScheduleDataRemoteSource.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/CategorySelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/ColorSelectViewModel.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputContract.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputPresenter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategoryCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategoryListAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategorySelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategorySelectViewModel.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorCreateActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/colorSelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/listAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/ViewModelFactory.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/utils/dialogUtils/PigLeadBalanceCategoryDeleteDialog.kt
  CalenderView/app/src/main/res/layout/color_select.xml
  CalenderView/app/src/main/res/layout/input_balance_main.xml
  CalenderView/app/src/main/res/layout/sub_category_create.xml
  CalenderView/app/src/main/res/layout/sub_category_select.xml
  CalenderView/app/src/main/res/values/strings.xml
Labels: タスク, バグ, 優先度：中

#159 #146 #151 #152
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/PigLeadDatabase.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/CategoryListAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/CategorySelectActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/SubCategorySelectActivity.kt
  CalenderView/app/src/main/res/drawable/income_icon.png
  CalenderView/app/src/main/res/layout/category_list_cell.xml
  CalenderView/app/src/main/res/layout/input_balance_main.xml
Labels: タスク, 優先度：中

#163 #160 不具合解消
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/inputForm/InputBalanceActivity.kt
  CalenderView/app/src/main/res/layout/input_balance_main.xml
Labels: バグ

#166 Issue 165
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarPageFragment.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/CalendarViewModel.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListAdapter.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/calendar/ScheduleListBindings.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/BalanceData.kt
  CalenderView/app/src/main/java/com/non_name_hero/calenderview/data/source/local/SchedulesDao.kt
Labels: バグ
